services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME:-vaultpapi-server}
    env_file:
      - ./server/.env
    ports:
      - "${HOST_PORT:-30144}:${PORT:-8080}"
    networks:
      - ${NETWORK_NAME:-shared_net}
    restart: unless-stopped

networks:
  shared_net:
    external: true
